#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS topic_db;
CREATE DATABASE IF NOT EXISTS reply_db;
CREATE DATABASE IF NOT EXISTS course_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS email_db;
CREATE DATABASE IF NOT EXISTS auth_server_db;

CREATE USER IF NOT EXISTS '${MYSQL_USER_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON user_db.* TO '${MYSQL_USER_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_TOPIC_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_TOPIC_PASSWORD}';
GRANT ALL PRIVILEGES ON topic_db.* TO '${MYSQL_TOPIC_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_REPLY_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_REPLY_PASSWORD}';
GRANT ALL PRIVILEGES ON reply_db.* TO '${MYSQL_REPLY_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_COURSE_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_COURSE_PASSWORD}';
GRANT ALL PRIVILEGES ON course_db.* TO '${MYSQL_COURSE_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_NOTIFICATION_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_NOTIFICATION_PASSWORD}';
GRANT ALL PRIVILEGES ON notification_db.* TO '${MYSQL_NOTIFICATION_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_EMAIL_SERVICE}'@'%' IDENTIFIED BY '${MYSQL_EMAIL_PASSWORD}';
GRANT ALL PRIVILEGES ON email_db.* TO '${MYSQL_EMAIL_SERVICE}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_AUTH_SERVER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
GRANT ALL PRIVILEGES ON auth_server_db.* TO '${MYSQL_AUTH_SERVER}'@'%';

FLUSH PRIVILEGES;
EOF
